'use strict';
const assert=require('node:assert/strict'), G=require('./engine.js');
const copy=s=>JSON.parse(JSON.stringify(s));
const s=G.newGame(519);
assert.equal(Object.keys(G.DETAILS).length,14);
const old=copy(s); delete old.instructions;
old.players.forEach(p=>{delete p.position;delete p.attributes;delete p.foot;delete p.ambition;});
assert(G.validSave(old)); G.upgradeSave(old); assert(G.validSave(old));
assert.equal(old.players.length,s.players.length);
assert.deepEqual(G.upgradeSave(copy(old)),old,'migration must be idempotent');
const bad=copy(s);bad.players[0].attributes.passing=NaN;assert(!G.validSave(bad));
const tired={...s.players[5],position:'CB',fitness:35,atk:90,def:90,tech:90,pace:90};
const fresh={...tired,id:999,fitness:100,atk:76,def:76,tech:76,pace:76};
assert(G.lineupScore(fresh,'CB')>G.lineupScore(tired,'CB'));
s.players.find(p=>p.club===0 && p.pos!=='GK').injury=4;
const lineup=G.autoLineup(s);assert.equal(new Set(lineup).size,11);
assert(lineup.every(id=>G.available(G.player(s,id))));
assert.equal(G.player(s,lineup[0]).position,'GK');
for(const sort of ['priceAsc','priceDesc','ovr','stat']) {
  const ps=G.filterPlayers(s,{sort,position:'ST',foot:'left',stat:'finishing',minStat:40,maxPrice:90,minOvr:50});
  assert(ps.length>1);
  const score=p=>sort.startsWith('price')?G.askingPrice(s,p.id):sort==='stat'?p.attributes.finishing:G.ovr(p);
  ps.forEach((p,i)=>{assert.equal(p.position,'ST');assert.equal(p.foot,'left');assert(G.askingPrice(s,p.id)<=90);if(i)assert(sort==='priceAsc'?score(ps[i-1])<=score(p):score(ps[i-1])>=score(p));});
}
const lower=G.newGame(14,G.CLUBS.findIndex(c=>G.LEAGUES[c[4]].tier===3));lower.budget=9999;
const target=lower.players.find(p=>p.club>0 && lower.leagues[lower.clubs[p.club].league].tier===1 && G.canRelease(lower,p.id));
const demand=G.wageDemand(lower,target), before=JSON.stringify(lower);
assert(demand.salary>G.wage(target));
assert.equal(G.deal(lower,target.id,G.askingPrice(lower,target.id),null,false,G.wage(target)).ok,false);
assert.equal(JSON.stringify(lower),before,'rejected salary must not move money or ownership');
assert(G.deal(lower,target.id,G.askingPrice(lower,target.id),null,false,demand.salary).ok);
assert.equal(target.salary,demand.salary);assert.equal(target.club,0);
const first=G.startMatch(s);assert.equal(s.pending.minute,0);assert.equal(first.hg+first.ag,0);
const baseline=G.strength(s,0), positions=G.matchPositions(s,0);
assert(G.setInstruction(s,1,'movement','invert'));assert(G.setInstruction(s,1,'runs','forward'));
assert(!G.setInstruction(s,13,'movement','invert'));assert(!G.setInstruction(s,1,'movement','nonsense'));
assert.notDeepEqual(G.strength(s,0),baseline);
assert.notDeepEqual(G.matchPositions(s,0),positions);
assert(G.matchPositions(s,9).every(p=>p.x>=0&&p.x<=100&&p.y>=0&&p.y<=100));
const startIds=s.clubs[0].lineup.slice(); G.setTactics(s,'formation','5-3-2'); assert.deepEqual(s.clubs[0].lineup,startIds);
for(let i=0;i<45;i++)G.advanceMinute(s);
assert.equal(s.week,0);assert.equal(s.pending.minute,45);assert(G.validSave(copy(s)));
const snapshot=copy(s), homeGoals=s.pending.half.hg;
const bench=G.roster(s).find(p=>!startIds.includes(p.id)&&G.available(p));
assert(G.substitute(s,startIds[1],bench.id).ok);assert(!G.substitute(s,bench.id,startIds[1]).ok);
for(let i=45;i<90;i++)G.advanceMinute(s);
assert.equal(G.advanceMinute(s),null);assert(s.pending.half.hg>=homeGoals);
assert(s.pending.half.events.every(e=>e.minute>=1&&e.minute<=90));
const finished=copy(s.pending.half); G.playWeek(s);
assert.equal(s.week,1);assert.equal(s.pending,null);assert.deepEqual(s.lastMatch,finished);assert(G.validSave(copy(s)));
const replay=copy(snapshot);G.playWeek(snapshot);G.playWeek(replay);assert.deepEqual(snapshot,replay,'saved minute and RNG resume deterministically');
for(let i=0;i<3;i++){const week=s.week;assert(G.autoWeek(s));assert.equal(s.week,week+1);assert(G.validSave(copy(s)));}
assert.equal(s.cupPlan.rotation,false,'batch must restore cup preference');
console.log('PASS: migration, detailed stats, fitness selection, position/foot/price/stat filters, ambition salary rejection/payment, instructions, live minutes, substitutions, replay, batch progression.');
